meta-java: hsqldb: Add recipe
Fixes

ERROR: Nothing PROVIDES 'hsqldb' (but
meta-java/recipes-core/xml-commons/jaxme_0.5.2.bb
DEPENDS on or otherwise requires it)
ERROR: Required build target 'jaxme' has no buildable providers.
M

(From meta-java rev: 4b17ec8dfff02090e54ae6385d5f2c0fe5501e86)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Henning Heinold <heinold@inf.fu-berlin.de>