meta-java: llvm2.8: Fix build break discovred by unanchored regexp fix in bitbake
commit 23bd5300b4a99218a15f4f6b0ab4091d63a602a5 fixed a bug
in bitbake which exposed this latent problem where we were using

EXTRA_OECMAKE_append-arm it was being treated as
EXTRA_OECMAKE_append before the above mentioned fix and hence
all was fine but after this fix behavior changed and
it was just EXTRA_OECMAKE_append-arm and was causing build
breaks

| ../../lib/libLLVMTransformUtils.so: undefined reference to
`llvm::CallGraphNode::removeCallEdgeFor(llvm::CallSite)'
| ../../lib/libLLVMTransformUtils.so: undefined reference to
`llvm::CallGraph::getOrInsertFunction(llvm::Function const*)'
| ../../lib/libLLVMTransformUtils.so: undefined reference to
`llvm::CallGraphLinkVar'
| ../../lib/libLLVMScalarOpts.so: undefined reference to
`llvm::createInstructionCombiningPass()'
| collect2: error: ld returned 1 exit status
| make[2]: *** [bin/llc] Error 1
| make[2]: Leaving directory
`/work/yocto/poky/build/tmp/work/x86_64-poky-linux/llvm2.8-2.8-r2.1/llvm-2.8/build'
| make[1]: *** [tools/llc/CMakeFiles/llc.dir/all] Error 2
| make[1]: *** Waiting for unfinished jobs....

It also fixes the llvm-mc build for arm architecture

modified for INC-PR
bumped PR

(From meta-java rev: fe6f342de963a55f565dfdbb7de20d29977b4ad1)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Henning Heinold <heinold@inf.fu-berlin.de>

Conflicts:
	recipes-core/llvm/llvm2.8_2.8.bb