meta-security-isafw: isafw: Python3 compatibility + cleanup
This makes isafw compatible with Python2 and Python3:
- "import *" can only be used at module scope in Python3,
  "import isafw" is enough here
- print is no longer a valid statement and bb logging calls
  should better be used anyway (when possible - if not,
  normal print is used as fallback): when bb.error()
  logs a problem, bitbake is later able to detect that, leading
  to non-zero return status where before this change the build
  seemed to work fine

Error reporting with exc_info() did not include stack backtraces and
the output was not marked as ERROR:
Exception in plugin:  (<class 'TypeError'>, TypeError('must be str, not bytes',), <traceback object at 0x7fac7550ecc8

Now it is a bit more useful:
ERROR: Exception in plugin ISA_CVEChecker process_report():
Traceback (most recent call last):
  File "/work/ostro-os/meta-security-isafw/lib/isafw/isafw.py", line 126, in call_plugins
    method(*parameters, **keywords)
  File ".../meta-security-isafw/lib/isafw/isaplugins/ISA_cve_plugin.py", line 209, in process_report
    return CVEChecker.process_report()
  File ".../meta-security-isafw/lib/isafw/isaplugins/ISA_cve_plugin.py", line 104, in process_report
    self.process_report_type("html")
  File ".../meta-security-isafw/lib/isafw/isaplugins/ISA_cve_plugin.py", line 174, in process_report_type
    freport.write(stdout_value)
TypeError: must be str, not bytes

The code for calling methods in plugins had been copy-and-pasted
several times. Now there is just one copy in call_plugins(), with
one-line invocations elsewhere.

(From meta-security-isafw rev: 0ccc6097213a1de155cb9833a6b6ffe2efe77ee7)

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>