gstreamer1.0-plugins-bad_git: fix gst_structure_get() etc compiler warnings
 | ../../../gst-plugins-bad-1.7.1/sys/decklink/gstdecklinkaudiosrc.cpp: In function 'gboolean gst_decklink_audio_src_set_caps(GstBaseSrc*, GstCaps*)':
 | ../../../gst-plugins-bad-1.7.1/sys/decklink/gstdecklinkaudiosrc.cpp:315:59: error: missing sentinel in function call [-Werror=format=]
 |	    g_object_get (videosrc, "connection", &vconn, NULL);
 |							      ^
 | cc1plus: all warnings being treated as errors

For GStreamer functions declared with G_GNUC_NULL_TERMINATED,
ie __attribute__((__sentinel__)), gcc will generate a warning if the
last parameter passed to the function is not NULL (where a valid NULL
in this context is defined as zero with any pointer type).

The C callers to such functions within gst-plugins-bad use the C NULL
definition (ie ((void*)0)), which is a valid sentinel.

However the C++ NULL definition (ie 0L), is not a valid sentinel
without an explicit cast to a pointer type.

(From OE-core rev: 4ffc1c6ea67e65c21964fa119820b37725f5a5de)

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>