meta-openembedded: python-gdata: RDepend on python-xml instead of python-elementtree
* python-elementtree was folded to python-xml by this oe-core commit:
  commit 5f7206eba3953b7f29148ecfb791995773ee5fc7
  Author: Ross Burton <ross.burton@intel.com>
  Date:   Wed Feb 10 14:04:04 2016 +0000

    python: merge python-elementtree into python-xml

    python-xml depends on python-elementtree as the latter just contains a C library
    used by the former.  However there's no point to this split apart from
    increasing the number of packages, so merge -elementtree into python-xml.
* this is just band-aid for missing RPROVIDEs in that oe-core commit and be aware
  that upgrade-path on target is still broken (no RREPLACES/RCONFLICTS), so you'll
  need "upgrade" from python-elementtree manually on target.
* fixes:
  ERROR: Nothing RPROVIDES 'python-elementtree' (but /home/jenkins/oe/world/shr-core/meta-openembedded/meta-python/recipes-devtools/python/python-gdata_1.2.4.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'python-elementtree' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python-elementtree']
  NOTE: Runtime target 'python-gdata-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python-gdata-dev', 'python-elementtree']
  NOTE: Runtime target 'python-gdata' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python-gdata', 'python-elementtree']

From meta-openembedded rev: d2b9e9ed719d3889e7d746ed6c850fb649dd1e69